site_name: SeaSearch Manual
site_author: seafile
docs_dir: ./manual
site_url: https://haiwen.github.io/seasearch-docs/

repo_name: haiwen/seasearch-docs
repo_url: https://github.com/haiwen/seasearch-docs/
edit_uri: blob/master/manual

copyright: Copyright &copy; 2023 Seafile Ltd.

theme:
  name: material
  logo: media/seafile-transparent-1024.png
  favicon: media/favicon.ico
  palette:
    primary: white
    accent:

plugins:
  - search
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiwen/seasearch-docs/

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"
  - pymdownx.tabbed: 
      alternate_style: true
  - pymdownx.superfences: # allows 1) nesting of fences 2) custom fences 3) disable indented code
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - Introduction: README.md
  - Deployment and Usage:
    - Overview: usage/overview.md
    - Deploy SeaSearch: usage/deploy.md
    - Use and access SeaSearch APIs: usage/use_and_access_seasearch_apis.md
    - Https: usage/https.md
    - Backup and Restore: usage/backup_and_restore.md
  - Configuration: config/README.md
  - SeaSearch API: 
    - Overview: api/overview.md
    - API Authentication: api/authentication.md
    - Index management: api/index_management.md
    - Document operation: api/document_operation.md
    - Search document: api/search_document.md
